version: '3.8'
services:
  api:
    build: /api
    restart: always
    pull_policy: build
    depends_on:
      - db
    environment:
      - TZ=Europe/Moscow
      - DATASOURCE_URL=jdbc:postgresql://db:5432/fintech_api
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - SERVER_PORT=8083
      - ORIGINATION_GRPC_HOST=origination
      - ORIGINATION_GRPC_PORT=9094
    ports:
      - '8083:8083'

  origination:
    build: /origination
    restart: always
    pull_policy: build
    depends_on:
      - db
    environment:
      - TZ=Europe/Moscow
      - DATASOURCE_URL=jdbc:postgresql://db:5432/fintech_origination
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - GRPC_PORT=9094
      - SCORING_GRPC_HOST=scoring
      - SCORING_GRPC_PORT=9095
      - PRODUCT_ENGINE_GRPC_HOST=product-engine
      - PRODUCT_ENGINE_GRPC_PORT=9090
      - PAYMENT_GATE_GRPC_HOST=payment-gate
      - PAYMENT_GATE_GRPC_PORT=9096
      - SCHEDULER_INITIAL_DELAY=PT01M
      - SCHEDULER_INTERVAL=PT01M
      - EMAIL_SENDER_USERNAME=username@gmail.com
      - EMAIL_SENDER_PASSWORD=password
    ports:
      - '9094:9094'

  scoring:
    build: /scoring
    restart: always
    pull_policy: build
    environment:
      - TZ=Europe/Moscow
      - GRPC_PORT=9095
      - PRODUCT_ENGINE_GRPC_HOST=product-engine
      - PRODUCT_ENGINE_GRPC_PORT=9090
    ports:
      - '9095:9095'

  product-engine:
    build: /product-engine
    restart: always
    pull_policy: build
    depends_on:
      - db
    environment:
      - TZ=Europe/Moscow
      - DATASOURCE_URL=jdbc:postgresql://db:5432/fintech_product_engine
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
    ports:
      - '9090:9090'

  payment-gate:
    build: /payment-gate
    restart: always
    pull_policy: build
    depends_on:
      - db
    environment:
      - TZ=Europe/Moscow
      - SERVER_PORT=8087
      - GRPC_PORT=9096
      - DATASOURCE_URL=jdbc:postgresql://db:5432/fintech_payment_gate
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - ORIGINATION_GRPC_HOST=origination
      - ORIGINATION_GRPC_PORT=9094
      - PRODUCT_ENGINE_GRPC_HOST=product-engine
      - PRODUCT_ENGINE_GRPC_PORT=9090
      - MERCHANT_PROVIDER_REST_HOST=merchant-provider
      - MERCHANT_PROVIDER_REST_PORT=8085
      - SCHEDULER_INITIAL_DELAY=PT01M
      - SCHEDULER_INTERVAL=PT02M
    ports:
      - '9096:9096'
      - '8087:8087'

  merchant-provider:
    build: /merchant-provider
    restart: always
    pull_policy: build
    environment:
      - TZ=Europe/Moscow
      - SERVER_PORT=8085
      - DATASOURCE_URL=jdbc:postgresql://db:5432/fintech_merchant_provider
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - PAYMENT_GATE_REST_HOST=payment-gate
      - PAYMENT_GATE_REST_PORT=8087
      - SCHEDULER_INITIAL_DELAY=PT01M
      - SCHEDULER_INTERVAL=PT01M
    ports:
      - '8085:8085'

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker/pg-init-scripts:/docker-entrypoint-initdb.d

volumes:
  db:
    driver: local