spring:
  config:
    import:
      - classpath:/application-exporter.yml
  liquibase:
    change-log: classpath:/db/db.changelog-master.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
    listener:
      ack-mode: manual_immediate

grpc:
  port: 9090
  enable-reflection: true
overdue:
  scheduling:
    cron-interval: ${SCHEDULER_INTERVAL_IN_CRON}
    tz: ${TZ}