server:
  port: ${SERVER_PORT}
grpc:
  port: ${GRPC_PORT}
  enable-reflection: true
spring:
  liquibase:
    change-log: classpath:/db/db.changelog-master.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
api:
  client:
    origination:
      grpc:
        host: ${ORIGINATION_GRPC_HOST}
        port: ${ORIGINATION_GRPC_PORT}
    merchant-provider:
      rest:
        host: ${MERCHANT_PROVIDER_REST_HOST}
        port: ${MERCHANT_PROVIDER_REST_PORT}
    product-engine:
      grpc:
        host: ${PRODUCT_ENGINE_GRPC_HOST}
        port: ${PRODUCT_ENGINE_GRPC_PORT}
payment:
  scheduling:
    interval: ${SCHEDULER_INTERVAL}
    initial-delay: ${SCHEDULER_INITIAL_DELAY}