openapi: 3.0.0
info:
  title: Payment gate
  description: Payment gate
  version: 0.0.1
servers:
  - url: http://localhost:8087/api/v1
    description: Development server
paths:
  /payment/loan:
    post:
      summary: Handle loan payment from client
      tags:
        - PaymentGate
      operationId: loanPayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanPaymentRequest'
      responses:
        '200':
          description: Successful operation
        'default':
          description: Operation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    LoanPaymentRequest:
      type: object
      required:
        - client_email
        - agreement_number
        - amount
      properties:
        client_email:
          type: string
          format: email
          example: test@mail.ru
          description: The user who made the payment
        agreement_number:
          type: string
          format: uuid
          example: 9e04bac4-69de-429c-ac03-3fc22f6c94e3
          description: Agreement to which the payment is linked
        amount:
          type: number
          minimum: 0
          exclusiveMinimum: true
          example: 60250
          description: Payment amount
    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          example: 404
        message:
          type: string
          example: Payment not found
  
