openapi: 3.0.3
info:
  title: Test endpoints
  version: 1.0.0
servers:
  - url: 'http://localhost:8085/api/v1'
paths:
  /test/payment/status/{id}:
    put:
      summary: Update payment status
      tags:
        - Test
      operationId: updateStatus
      parameters:
        - name: id
          in: path
          description: Payment UUID
          required: true
          schema:
            type: string
            format: uuid
            example: e16d24c5-2a4f-4e56-897c-f18c63e9764e
        - name: status
          in: query
          description: New status
          required: true
          schema:
            $ref: './merchant-provider.yaml/#/components/schemas/PaymentStatus'
      responses:
        '200':
          description: Successful operation
