spring:
  config:
    import:
      - classpath:/application-exporter.yml
  liquibase:
    change-log: classpath:/db/db.changelog-master.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
    listener:
      ack-mode: manual_immediate
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SENDER_USERNAME}
    password: ${EMAIL_SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
grpc:
  port: ${GRPC_PORT}
  enable-reflection: true
api:
  client:
    scoring:
      grpc:
        host: ${SCORING_GRPC_HOST}
        port: ${SCORING_GRPC_PORT}
    product-engine:
      grpc:
        host: ${PRODUCT_ENGINE_GRPC_HOST}
        port: ${PRODUCT_ENGINE_GRPC_PORT}
    payment-gate:
      grpc:
        host: ${PAYMENT_GATE_GRPC_HOST}
        port: ${PAYMENT_GATE_GRPC_PORT}
scoring:
  scheduling:
    initial-delay: ${SCHEDULER_INITIAL_DELAY}
    interval: ${SCHEDULER_INTERVAL}
